version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  colored:
    (): colorlog.ColoredFormatter
    format: '%(asctime)s - %(name)s - %(log_color)s%(levelname)s - %(blue)s%(message)s'
    datefmt: '%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: app.log
root:
  level: DEBUG
  handlers: [console, file]
disable_existing_loggers: false
