bot:
  token: ""
  log_chat: -1001234567890
  superusers:
    - 666
  botapi:
    # can be official (api.telegram.org)
    type: official
#    # or local (setup in docker-compose.yml)
#    type: local
#    botapi_url: "http://telegram-bot-api:8081"
#    file_url: "http://nginx:80"
db:
  type: postgresql
  connector: asyncpg
  host: localhost
  port: 5432
  login: postgres
  password: postgres
  name: aiogram_template_bot
